<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    /**
     * Eloquent pivot inserts don't set the `id` value when syncing variant
     * images, so the UUID primary key must be generated by the database.
     */
    public function up(): void
    {
        Schema::table('variant_images', function (Blueprint $table) {
            $table->uuid('id')->default(DB::raw('(UUID())'))->change();
        });
    }

    public function down(): void
    {
        Schema::table('variant_images', function (Blueprint $table) {
            $table->uuid('id')->default(null)->change();
        });
    }
};
